{% set name = "pti-gpu-unitrace" %}
{% set version = "2.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/intel/pti-gpu/archive/refs/tags/unitrace-{{ version }}.tar.gz
  sha256: 73e974dc5b6c16b4340be6a87706d134f0e308292d1a2a11e4d1b12b4cadd1cd

build:
  number: 0
  skip: true  # [not linux]
  ignore_run_exports:
    - dpcpp-cpp-rt

requirements:
  build:
    - cmake >=3.29
    - ninja >=1.11.1
    - {{ compiler('cxx') }}
    - {{ compiler('dpcpp') }} >=2024.1.0
    - {{ stdlib('c') }}
  host:
    - level-zero-devel >=1.17.6
    - ocl-icd  # [linux]
    - khronos-opencl-icd-loader  # [not linux]
    # These packages are not required during build, but we want proper version
    # export for runtime:
    # https://github.com/conda-forge/intel-compiler-repack-feedstock/issues/37
    - intel-cmplr-lib-rt
  run:
    # https://github.com/conda-forge/intel-compiler-repack-feedstock/issues/37
    - {{ pin_compatible('intel-cmplr-lib-rt', min_pin='x.x', max_pin='x') }}

test:
  commands:
    - unitrace --help

outputs:
  - name: {{ name }}
    files:
      # Need to filter files so that we avoid installing dev dependencies from
      # itt libraray...
      - bin/unitrace  #[linux]
      - bin/libunitrace_tool.so  #[linux]

about:
  home: https://github.com/intel/pti-gpu
  summary: 'Unified Tracing and Profiling Tool'
  description: |
    This a performnce tool for Intel(R) oneAPI applications. It traces and
    profiles host/device activites, interactions and hardware utilizations for
    Intel(R) GPU applications.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://github.com/intel/pti-gpu
  dev_url: https://github.com/intel/pti-gpu

extra:
  recipe-maintainers:
    - ZzEeKkAa
    - oleksandr-pavlyk
