{% set name = "intel-pti" %}
{% set version = "0.10.0" %}
{% set version_pkg = version | replace("-", ".") %}
{% set so_version = version.split('.')[0] ~ "." ~ version.split('.')[1] %}
{% set so_version_major = version.split('.')[0] %}

{% set unitrace_version_match = load_file_regex(
  load_file="tools/unitrace/src/version.h",
  regex_pattern='#define\s+UNITRACE_VERSION\s+"(.+)"') %}
{% set unitrace_version = unitrace_version_match[1] %}

package:
  name: {{ name|lower }}-split
  version: {{ version_pkg }}

source:
  url: https://github.com/intel/pti-gpu/archive/refs/tags/pti-{{version}}.tar.gz
  sha256: 6b712931b4b9af7c57dc19cfffeeafa1806a1f8a6464d1a781e6a83acb409b3a
  patches:
    - patches/0001-Link-spdlog-dynamically.patch

build:
  number: 1
  skip: true  # [not linux]
  ignore_run_exports:
    - dpcpp-cpp-rt
    - spdlog >=1.14.1

requirements:
  build:
    - cmake >=3.29
    - ninja >=1.11.1
    - {{ compiler('cxx') }} # that is lilbstc++ for both rt and build
    # FIXME: use 2024.2.1 compiler, once available. There is a queue_id feature
    #  missing
    - {{ stdlib('c') }} # glibc for build/rt
  host:
    - level-zero-devel >=1.17.6 # level zero for build/rt
    - ocl-icd  # [linux]
    - khronos-opencl-icd-loader  # [not linux]
    - spdlog >=1.14.1
    # TODO: https://github.com/conda-forge/spdlog-feedstock/issues/52
    #   remove once fmt is in run_export of spdlog.
    - fmt
    # These packages are not required during build, but we want proper version
    # export for runtime:
    - intel-cmplr-lib-rt # this is the dependency for dpcpp rt

outputs:
  - name: {{ name }}
    script: install.sh
    version: {{ version_pkg }}
    run_exports:
        - {{ pin_subpackage(name, max_pin='x.x') }}
    requirements:
      build:
        - cmake >=3.29
        - ninja >=1.11.1
        - {{ compiler('cxx') }}
        - {{ stdlib('c') }}
      host:
        - level-zero-devel >=1.17.6
        - ocl-icd  # [linux]
        - khronos-opencl-icd-loader  # [not linux]
        - spdlog >=1.14.1
        # TODO: https://github.com/conda-forge/spdlog-feedstock/issues/52
        #   remove once fmt is in run_export of spdlog.
        - fmt
        # These packages are not required during build, but we want proper version
        # export for runtime:
        - intel-cmplr-lib-rt
    test:
      commands:
        - test -f $PREFIX/lib/libpti.so  # [linux]
        - test -f $PREFIX/lib/libpti_view.so  # [linux]
        - test -f $PREFIX/lib/libpti.so.{{ so_version }}  # [linux]
        - test -f $PREFIX/lib/libpti_view.so.{{ so_version }}  # [linux]
    about:
      summary: 'Profiling Tools Interfaces for GPU2'
      description: |
        A PTI library for Intel(R) oneAPI applications. 
  
  - name: pti-gpu-unitrace
    script: build.sh
    version: {{ unitrace_version }}
    requirements:
      build:
        - cmake >=3.29
        - ninja >=1.11.1
        - {{ compiler('cxx') }}
        - {{ compiler('dpcpp') }} >=2024.2.1
        - {{ stdlib('c') }}
      host:
        - level-zero-devel >=1.17.6
        - ocl-icd  # [linux]
        - khronos-opencl-icd-loader  # [not linux]
        - impi-devel
        # TODO: add ittapi-static once it is available
        # - ittapi-static
        # These packages are not required during build, but we want proper version
        # export for runtime:
        - intel-cmplr-lib-rt
    test:
      commands:
        - unitrace --help
    about:
      home: https://github.com/intel/pti-gpu
      summary: 'Unified Tracing and Profiling Tool'
      description: |
        A performnce tool for Intel(R) oneAPI applications. It traces and
        profiles host/device activites, interactions and hardware utilizations for
        Intel(R) GPU applications.
      license: MIT
      license_family: MIT
      license_file: LICENSE
      doc_url: https://github.com/intel/pti-gpu
      dev_url: https://github.com/intel/pti-gpu

about:
  home: https://github.com/intel/pti-gpu
  summary: 'Profiling Tools Interfaces for GPU'
  description: |
    This a PTI library for Intel(R) oneAPI applications. 
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://github.com/intel/pti-gpu
  dev_url: https://github.com/intel/pti-gpu

extra:
  recipe-maintainers:
    - ZzEeKkAa
    - oleksandr-pavlyk
    - mschilling0
